---

- hosts: all
  become: true
  tasks:

  - name: install docker
    yum:
      name: docker-ce
    when: ansible_distribution == "RedHat"

  - name: copy docker compose files
    ansible.builtin.copy:
      src: /your/path/to/source/
      dest: /your/path/to/destination/
      owner: root
      group: root
      mode: '0644'

  - name: run docker compose
    become: True
    shell:
      cmd: "docker compose up -d"
      chdir: /home/ec2-user/your/docker_compose_file_location